with open('/root/Project-Genie/briefing.py', 'w') as f:
    f.write('import sentry_sdk\n')
    f.write('from integrations.gmail import get_unread_emails\n')
    f.write('from integrations.calendar import get_todays_events\n')
    f.write('from ai_helper import get_ai_response\n')
    f.write('from datetime import datetime\n')
    f.write('\n')
    f.write('\n')
    f.write('def get_briefing():\n')
    f.write('    try:\n')
    f.write('        emails = get_unread_emails()\n')
    f.write('    except Exception as e:\n')
    f.write('        sentry_sdk.capture_exception(e)\n')
    f.write('        emails = "Could not retrieve emails at this time."\n')
    f.write('    try:\n')
    f.write('        calendar = get_todays_events()\n')
    f.write('    except Exception as e:\n')
    f.write('        sentry_sdk.capture_exception(e)\n')
    f.write('        calendar = "Could not retrieve calendar at this time."\n')
    f.write('    day = datetime.now().strftime("%A, %B %d")\n')
    f.write('    prompt = (\n')
    f.write('        "You are Genie, a warm and professional personal assistant. "\n')
    f.write('        "Write a concise morning briefing for today " + day + ". "\n')
    f.write('        "Be friendly and encouraging. "\n')
    f.write('        "Start with Good Morning and end with a motivating closing line.\\n\\n"\n')
    f.write('        "EMAILS:\\n" + emails + "\\n\\n"\n')
    f.write('        "CALENDAR:\\n" + calendar\n')
    f.write('    )\n')
    f.write('    try:\n')
    f.write('        return get_ai_response(prompt)\n')
    f.write('    except Exception as e:\n')
    f.write('        sentry_sdk.capture_exception(e)\n')
    f.write('        return "Good Morning! I was unable to generate your briefing today. Have a great day!"\n')
print('briefing.py written successfully')
