with open('/root/Project-Genie/integrations/gmail.py', 'w') as f:
    f.write('import sentry_sdk\n')
    f.write('from googleapiclient.discovery import build\n')
    f.write('from utils.google_auth import get_credentials\n')
    f.write('\n')
    f.write('\n')
    f.write('def get_unread_emails():\n')
    f.write('    try:\n')
    f.write('        creds = get_credentials()\n')
    f.write('        service = build("gmail", "v1", credentials=creds)\n')
    f.write('        results = service.users().messages().list(\n')
    f.write('            userId="me", labelIds=["UNREAD"], maxResults=5\n')
    f.write('        ).execute()\n')
    f.write('        messages = results.get("messages", [])\n')
    f.write('        if not messages:\n')
    f.write('            return "No unread emails!"\n')
    f.write('        reply = "You have " + str(len(messages)) + " unread emails:\\n"\n')
    f.write('        for msg in messages:\n')
    f.write('            try:\n')
    f.write('                detail = service.users().messages().get(\n')
    f.write('                    userId="me", id=msg["id"], format="metadata"\n')
    f.write('                ).execute()\n')
    f.write('                headers = {h["name"]: h["value"] for h in detail["payload"]["headers"]}\n')
    f.write('                reply += "- " + headers.get("Subject", "No Subject") + " from " + headers.get("From", "Unknown") + "\\n"\n')
    f.write('            except Exception as e:\n')
    f.write('                sentry_sdk.capture_exception(e)\n')
    f.write('                reply += "- Could not load one email\\n"\n')
    f.write('        return reply\n')
    f.write('    except Exception as e:\n')
    f.write('        sentry_sdk.capture_exception(e)\n')
    f.write('        return "I was unable to retrieve your emails at this time."\n')
print('gmail.py written successfully')
